// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'flutter_services_test.dart' as prefix0;
import 'package:flutter/src/services/text_input.dart' as prefix1;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"ClassWithTextCapitalization",
            r".ClassWithTextCapitalization",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 2],
            const <int>[3, 4, 5, 6, 7, 1],
            const <int>[],
            -1,
            {},
            {},
            {
              r"": (b) => (
                      {textCapitalization =
                          prefix1.TextCapitalization.sentences}) =>
                  b
                      ? new prefix0.ClassWithTextCapitalization(
                          textCapitalization: textCapitalization)
                      : null
            },
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(r"textCapitalization", 33797, 0,
            const prefix0.Reflector(), -1, -1, -1, null, null),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, -1, -1, 1),
        new r.MethodMirrorImpl(r"", 0, 0, -1, -1, -1, null, const <int>[0],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, null,
            const <int>[1], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"toString", 131074, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1, null,
            const <int>[2], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(
            r"textCapitalization",
            47110,
            2,
            const prefix0.Reflector(),
            -1,
            -1,
            -1,
            null,
            null,
            null,
            #textCapitalization),
        new r.ParameterMirrorImpl(r"other", 16390, 3, const prefix0.Reflector(),
            null, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 5,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix0.ClassWithTextCapitalization],
      1,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"textCapitalization": (dynamic instance) => instance.textCapitalization
      },
      {},
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
